### ISSUE TITLE
DIAGRAMA DE CLASES EN ARCHITEC

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/actividad-3-practica-architect-saul19bautista#1]
[Saul_Reporte Diagrama de clases.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-saul19bautista/files/12554360/Saul_Reporte.Diagrama.de.clases.pdf)

**Comment by Edwin14459** [comment]
Portada: Excelente: 25 puntos
Procedimiento: Excelente “cumple con lo requerido” 25 puntos
Figuras, ilustraciones y fotografías: Notable: 22 puntos 
Resultados y conclusiones: Excelente “muestra su conclusión y resultado final” 25 puntos
Puntos totales: 97
Calificación final: 19.4 / 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
